# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 11:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geocode', models.CharField(max_length=12)),
                ('nome', models.CharField(max_length=50)),
                ('meso', models.CharField(max_length=50)),
                ('micro', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'municipios',
                'db_table': 'municipios',
                'verbose_name': 'municipio',
                'ordering': ['nome'],
            },
        ),
    ]
